# Copyright (C) 2014-2019 jim
#
# This file is not part of GNU Emacs.
#
# License
#
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

language: emacs-lisp

# Cache stable Emacs binaries, packages and Cask
cache:
  apt: true
  timeout: 604800
  directories:
    - "$HOME/emacs"
    # Cache AC PHP dependencies
    - ".cask/"
    # Cache Cask bootstrap dependencies
    - "$HOME/.emacs.d/.cask"

# Allow Emacs snapshot builds to fail and don't wait for it
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=git-snapshot
    - env: EMACS_VERSION=26.1
    - env: EMACS_VERSION=27.2

git:
  depth: 1

dist: trusty

env:
  matrix:
    - EMACS_VERSION=26.1
    - EMACS_VERSION=27.2
    - EMACS_VERSION=25.3
    - EMACS_VERSION=git-snapshot
  global:
    - PATH="$HOME/bin:$HOME/.cask/bin:$HOME/.evm/bin:$PATH"

before_install:
  # Setup Emacs Version Manager
  - git clone -q --depth=1 https://github.com/rejeep/evm.git $HOME/.evm
  - evm config path /tmp

install:
  # Install Emacs (according to $EMACS_VERSION) and Cask
  - evm install emacs-$EMACS_VERSION-travis --use --skip
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

before_script:
  # Configure $EMACS_MAJOR_VERSION
  - EMACS_MAJOR_VERSION="$(echo $EMACS_VERSION | cut -d '.' -f 1)"

script:
  - make help
  - make init
  # The 'checkdoc-file' present on Emacs >= 25.1
  # - '[[ "$EMACS_MAJOR_VERSION" = "24" ]] || make checkdoc'
  - make test

notifications:
  email: false
